"""SVG → Markdown : texte en ordre de lecture, structure de diagramme (Mermaid), éléments nommés, couleurs.

Un SVG est du XML : tout ce qui est textuel est récupérable avec certitude.
Ce qui est purement graphique (icône, courbe, illustration) ne l'est pas : le
convertisseur le signale et produit un rendu PNG pour lecture visuelle.
"""
from __future__ import annotations

import base64
import math
import re
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from .core import Ctx, Result, Unsupported, engine
from .fmt_diagram import (Graph, excalidraw_from_svg_comments, graph_from_excalidraw, graph_from_graphviz_svg,
                          graph_from_mermaid_svg, parse_mxfile, to_mermaid)
from .util import clean_text, esc_inline, fence, html_to_text, local, parse_xml, parse_xml_keep_comments

SVG = "http://www.w3.org/2000/svg"
XLINK = "http://www.w3.org/1999/xlink"
_SKIP = {"defs", "style", "script", "metadata", "namedview", "clipPath", "mask", "symbol", "pattern", "filter",
         "linearGradient", "radialGradient", "marker", "title", "desc", "font", "font-face", "glyph"}
_SHAPES = {"rect", "circle", "ellipse", "path", "line", "polyline", "polygon"}
_GENERIC_ID = re.compile(r"(?i)^(g|path|rect|circle|ellipse|line|polygon|polyline|text|tspan|use|defs|svg|layer|"
                         r"clip|mask|clippath|lineargradient|radialgradient|stop|image|filter|group|"
                         r"artboard|frame|vector|shape|rectangle|union|subtract|mask_group|calque|"
                         r"[a-z]+(_|-)?\d+)\s*[-_]?\d*$")
_AUTO_DESC = re.compile(r"(?i)^(created with|generated by|generator:|made with|svg (?:document|image)|untitled)")
_COLOR = re.compile(r"^(#[0-9a-fA-F]{3,8}|rgba?\([^)]*\)|hsla?\([^)]*\)|[a-zA-Z]+)$")
_IGNORE_COLORS = {"none", "currentcolor", "inherit", "transparent", "initial", "context-fill", "context-stroke",
                  "black", "white", "#000", "#000000", "#fff", "#ffffff"}    # noir/blanc : valeurs par défaut, sans information


def _f(v: Optional[str], default: float = 0.0) -> float:
    if v is None:
        return default
    m = re.match(r"\s*(-?\d*\.?\d+(?:[eE][-+]?\d+)?)", v)
    return float(m.group(1)) if m else default


def parse_transform(s: Optional[str]) -> Tuple[float, float, float, float, float, float]:
    """« translate(10 20) scale(2) rotate(45) matrix(…) » → matrice affine (a,b,c,d,e,f)."""
    m = (1.0, 0.0, 0.0, 1.0, 0.0, 0.0)
    if not s:
        return m
    for name, args in re.findall(r"(\w+)\s*\(([^)]*)\)", s):
        v = [float(x) for x in re.findall(r"-?\d*\.?\d+(?:[eE][-+]?\d+)?", args)]
        t = m
        if name == "translate" and v:
            t = (1, 0, 0, 1, v[0], v[1] if len(v) > 1 else 0)
        elif name == "scale" and v:
            t = (v[0], 0, 0, v[1] if len(v) > 1 else v[0], 0, 0)
        elif name == "rotate" and v:
            a = math.radians(v[0])
            ca, sa = math.cos(a), math.sin(a)
            t = (ca, sa, -sa, ca, 0, 0)
            if len(v) >= 3:
                cx, cy = v[1], v[2]
                t = (ca, sa, -sa, ca, cx - ca * cx + sa * cy, cy - sa * cx - ca * cy)
        elif name == "matrix" and len(v) == 6:
            t = tuple(v)  # type: ignore[assignment]
        elif name == "skewx" and v:
            t = (1, 0, math.tan(math.radians(v[0])), 1, 0, 0)
        elif name == "skewy" and v:
            t = (1, math.tan(math.radians(v[0])), 0, 1, 0, 0)
        else:
            continue
        m = _mul(m, t)  # type: ignore[arg-type]
    return m


def _mul(p, q):
    a1, b1, c1, d1, e1, f1 = p
    a2, b2, c2, d2, e2, f2 = q
    return (a1 * a2 + c1 * b2, b1 * a2 + d1 * b2, a1 * c2 + c1 * d2, b1 * c2 + d1 * d2,
            a1 * e2 + c1 * f2 + e1, b1 * e2 + d1 * f2 + f1)


def _apply(m, x: float, y: float) -> Tuple[float, float]:
    return m[0] * x + m[2] * y + m[4], m[1] * x + m[3] * y + m[5]


def _style(el: ET.Element) -> Dict[str, str]:
    st = el.get("style")
    out: Dict[str, str] = {}
    if st:
        for part in st.split(";"):
            if ":" in part:
                k, v = part.split(":", 1)
                out[k.strip().lower()] = v.strip()
    return out


def _hidden(el: ET.Element) -> bool:
    st = _style(el)
    if (st.get("display") == "none" or el.get("display") == "none"
            or st.get("visibility") in ("hidden", "collapse") or el.get("visibility") in ("hidden", "collapse")):
        return True
    try:
        return float(st.get("opacity", el.get("opacity", "1"))) == 0.0 and local(el.tag) != "g"
    except ValueError:
        return False


class TextItem:
    __slots__ = ("text", "x", "y", "size", "order", "anchor", "lines")

    def __init__(self, text: str, x: float, y: float, size: float, order: int, anchor: str = "start", lines: int = 1):
        self.text, self.x, self.y, self.size, self.order = text, x, y, size, order
        self.anchor, self.lines = anchor, lines


class SvgConverter:
    def __init__(self, root: ET.Element, raw: bytes, ctx: Ctx, path: Path):
        self.root, self.raw, self.ctx, self.path = root, raw, ctx, path
        self.texts: List[TextItem] = []
        self.comment_texts: List[str] = []      # texte connu seulement par des commentaires (matplotlib) : absent du XML visible
        self.tooltips: List[str] = []
        self.links: List[Tuple[str, str]] = []
        self.names: List[str] = []
        self.counts: Counter = Counter()
        self.colors: Counter = Counter()
        self.images: List[str] = []
        self.order = 0
        self.embedded = 0

    # ------------------------------------------------------------------
    def run(self) -> Result:
        root = self.root
        title = next((clean_text("".join(c.itertext())).strip() for c in root if local(c.tag) == "title"), "")
        desc = next((clean_text("".join(c.itertext())).strip() for c in root if local(c.tag) == "desc"), "")
        if _AUTO_DESC.match(desc):
            desc = ""
        meta = self.metadata()
        generator = self.generator(meta)
        graph, kind = self.recognize_graph()
        self.walk(root, (1, 0, 0, 1, 0, 0), 12.0, 0)
        if graph is None or not graph.is_meaningful():
            graph, kind = self.geometric_graph()
            if graph is not None:
                self.ctx.warn("schéma reconstitué d'après la position des formes, traits et flèches : à vérifier sur le rendu (--render)")
        ordered = self.reading_order()
        w, h, vb = root.get("width", ""), root.get("height", ""), root.get("viewBox", "")
        size_txt = self.size_text(w, h, vb)
        n_shapes = sum(self.counts[k] for k in _SHAPES)
        n_text = len(ordered)

        parts: List[str] = []
        head_title = title or meta.get("title") or self.path.stem
        parts.append(f"# {esc_inline(head_title)}")
        facts = [f"SVG {size_txt}".strip()]
        if generator:
            facts.append(generator)
        inv = ", ".join(f"{n} {k}" for k, n in self.counts.most_common(6) if n)
        if inv:
            facts.append(f"{sum(self.counts.values())} éléments ({inv})")
        parts.append("> " + " · ".join(facts))
        if desc or meta.get("description"):
            parts.append(esc_inline(desc or meta["description"]))
        has_graph = graph is not None and graph.is_meaningful()
        title_of_text = "Texte (ordre de lecture)"
        if has_graph:
            parts.append(f"## Diagramme ({kind})\n\n{to_mermaid(graph)}")
            shown = {re.sub(r"\s+", " ", t).strip() for t in list(graph.texts()) + list(getattr(graph, "shown", []))}
            rest = [t for t in ordered if re.sub(r"\s+", " ", t).strip() not in shown]
            ordered, title_of_text = rest, "Autres textes"      # les étiquettes du diagramme figurent déjà dans le graphe
        if ordered:
            lines = [f"- {esc_inline(t)}" for t in ordered]
            parts.append(f"## {title_of_text}\n\n" + "\n".join(lines))
        if self.tooltips and not (graph is not None and graph.is_meaningful()):
            uniq = list(dict.fromkeys(self.tooltips))[:40]
            parts.append("## Infobulles (<title>)\n\n" + "\n".join(f"- {esc_inline(t)}" for t in uniq))
        if self.links:
            parts.append("## Liens\n\n" + "\n".join(f"- [{esc_inline(t) or h}]({h})" for t, h in list(dict.fromkeys(self.links))[:40]))
        names = [n for n in dict.fromkeys(self.names) if not _GENERIC_ID.match(n)][:30]
        if names:
            parts.append("## Groupes / calques nommés\n\n" + ", ".join(f"`{n}`" for n in names))
        if self.colors and not has_graph:
            top = ", ".join(f"`{c}` ({n})" for c, n in self.colors.most_common(8))
            parts.append(f"## Couleurs\n\n{top}")
        if self.images:
            parts.append("## Images intégrées\n\n" + "\n".join(self.images))
        # source simplifiée : utile quand le SVG est petit (icône, logo) ou sans graphe reconnu
        simplified = simplify_svg(self.raw)
        include_source = len(simplified) <= 8000 and not (graph is not None and graph.is_meaningful())
        if include_source:
            parts.append("## Source SVG (simplifiée)\n\n" + fence(simplified, "svg"))
        # lecture visuelle
        stats = getattr(self, "geo_stats", {})
        if not has_graph and stats.get("connectors", 0) >= 2 and stats.get("shapes", 0) >= 2:
            self.vision(parts, f"schéma dont les liens n'ont pas pu être déduits ({stats['attached']} trait(s) rattaché(s) sur {stats['connectors']}) — à relire sur le rendu")
        elif not has_graph:
            if n_text == 0 and n_shapes > 0:
                self.vision(parts, "SVG sans texte : icône, logo ou illustration — à décrire depuis le rendu")
            elif n_shapes > 40 and n_text < 25:
                self.vision(parts, "SVG graphique (graphique/illustration) : le texte extrait ne décrit pas l'image — à décrire depuis le rendu")
        md = "\n\n".join(parts)
        res = Result(markdown=md, fmt="svg", engine="native", title=head_title)
        res.source_text = self.source_text()
        res.stats["partial_source"] = True
        res.meta.update({k: v for k, v in meta.items() if k in ("author", "created", "license")})
        return res

    # ------------------------------------------------------------------
    def vision(self, parts: List[str], reason: str) -> None:
        rendered = None
        try:
            from .external import render_svg

            rendered = render_svg(self.path, self.ctx)
        except Exception:
            rendered = None
        target = rendered or str(self.path)
        self.ctx.need_vision("svg", target, reason)
        if rendered:
            parts.append(f"![rendu du SVG]({rendered})")
        parts.append(f"> **[À COMPLÉTER : description visuelle]** {reason}.")

    @staticmethod
    def size_text(w: str, h: str, vb: str) -> str:
        if w and h:
            return f"{w}×{h}" + (f" (viewBox {vb})" if vb else "")
        return f"viewBox {vb}" if vb else ""

    def metadata(self) -> Dict[str, str]:
        out: Dict[str, str] = {}
        md = next((c for c in self.root if local(c.tag) == "metadata"), None)
        if md is not None:
            for el in md.iter():
                n, t = local(el.tag), clean_text("".join(el.itertext()) if len(el) == 0 else "").strip()
                if not t:
                    continue
                if n == "title" and "title" not in out and not t.lower().startswith(("matplotlib", "image/")):
                    out["title"] = t
                elif n == "title":
                    out.setdefault("generator_title", t)
                elif n == "description":
                    out.setdefault("description", t)
                elif n in ("date", "created"):
                    out.setdefault("created", t)
                elif n == "creator":
                    out.setdefault("author", t)
            for el in md.iter():
                if local(el.tag) == "License":
                    out.setdefault("license", el.get("{http://www.w3.org/1999/02/22-rdf-syntax-ns#}about", ""))
        return out

    def generator(self, meta: Dict[str, str]) -> str:
        root = self.root
        ver = root.get("{http://www.inkscape.org/namespaces/inkscape}version")
        if ver:
            return f"Inkscape {ver.split()[0]}"
        if meta.get("generator_title", "").lower().startswith("matplotlib"):
            return meta["generator_title"]
        for node in root.iter():
            if node.tag is ET.Comment:
                t = (node.text or "").strip()
                m = re.search(r"(?i)(generator:\s*|generated by\s*)([^\n]+)", t)
                if m:
                    return re.sub(r"\s+", " ", m.group(2))[:60].strip(" ,;.")
                break
        if root.get("content", "").lstrip().startswith("<mxfile") or "&lt;mxfile" in root.get("content", ""):
            return "draw.io"
        if str(root.get("id", "")).startswith("mermaid"):
            return "Mermaid"
        return ""

    # -- graphe ---------------------------------------------------------
    def recognize_graph(self) -> Tuple[Optional[Graph], str]:
        root = self.root
        content = root.get("content", "")
        if "<mxfile" in content or "<mxGraphModel" in content:
            try:
                pages = parse_mxfile(parse_xml(content.encode("utf-8")))
                if pages:
                    g = pages[0][1]
                    if g.is_meaningful():
                        return g, "draw.io"
            except Exception:
                pass
        scene = excalidraw_from_svg_comments(root)
        if scene:
            g = graph_from_excalidraw(scene)
            if g.is_meaningful():
                return g, "Excalidraw"
        g = graph_from_graphviz_svg(root)
        if g is not None and g.is_meaningful():
            return g, "Graphviz"
        g = graph_from_mermaid_svg(root)
        if g is not None and g.is_meaningful():
            return g, "Mermaid"
        return None, ""

    def geometric_graph(self) -> Tuple[Optional[Graph], str]:
        """Schéma dessiné sans structure (Inkscape, Illustrator, Figma, script…) : liens déduits des formes, traits et flèches."""
        self.geo_stats: Dict[str, int] = {}
        if not self.texts:
            return None, ""
        from .svg_geometry import infer_graph

        vb = [float(v) for v in re.findall(r"-?\d*\.?\d+", self.root.get("viewBox", ""))]
        canvas = (vb[2], vb[3]) if len(vb) == 4 else (_f(self.root.get("width")), _f(self.root.get("height")))
        try:
            g, self.geo_stats = infer_graph(self.root, self.texts, (parse_transform, _mul, _apply, _style, _hidden), canvas)
        except Exception:
            return None, ""
        if g is not None and g.is_meaningful():
            return g, "déduit de la géométrie"
        return None, ""

    # -- parcours ---------------------------------------------------------
    def walk(self, el: ET.Element, m, size: float, depth: int) -> None:
        if depth > 200:
            return
        children = list(el)
        i = 0
        while i < len(children):
            ch = children[i]
            i += 1
            if ch.tag is ET.Comment:
                self.matplotlib_text(ch, children, i, m, size)
                continue
            if not isinstance(ch.tag, str):
                continue
            name = local(ch.tag)
            if name in _SKIP:
                if name == "title" and el is not self.root and (ch.text or "").strip():
                    self.tooltips.append(clean_text(" ".join((ch.text or "").split())))
                continue
            if _hidden(ch):
                continue
            cm = _mul(m, parse_transform(ch.get("transform")))
            fs = self.font_size(ch, size)
            self.color_of(ch)
            if name == "switch":
                for alt in ch:
                    if isinstance(alt.tag, str) and self.has_text(alt):
                        self.walk_single(alt, cm, fs, depth)
                        break
                continue
            self.walk_single(ch, cm, fs, depth)

    def walk_single(self, ch: ET.Element, cm, fs: float, depth: int) -> None:
        name = local(ch.tag)
        if name == "text":
            self.counts["text"] += 1
            self.add_text(ch, cm, fs)
        elif name == "foreignObject":
            self.counts["foreignObject"] += 1
            raw = ET.tostring(ch, encoding="unicode")
            inner = re.sub(r"^<[^>]*>|</[^>]*>\s*$", "", raw, count=1)
            txt = clean_text(html_to_text(inner)).strip()
            if txt:
                x, y = _apply(cm, _f(ch.get("x")), _f(ch.get("y")))
                self.add(" ".join(txt.split("\n")), x, y, fs)
        elif name == "image":
            self.counts["image"] += 1
            self.image(ch)
        elif name in _SHAPES:
            self.counts[name] += 1
            self.color_of(ch)
        elif name == "a":
            href = ch.get("{%s}href" % XLINK) or ch.get("href") or ""
            before = len(self.texts)
            self.walk(ch, cm, fs, 1)
            if href and not href.startswith("#"):
                label = " ".join(t.text for t in self.texts[before:])
                self.links.append((label, href))
        elif name in ("g", "svg"):
            if name == "g":
                self.counts["g"] += 1
                for key in ("{http://www.inkscape.org/namespaces/inkscape}label", "id", "aria-label", "data-name"):
                    v = ch.get(key)
                    if v and not v.startswith(("__", "svg")):
                        self.names.append(v.replace("_x5F_", "_").replace("_x20_", " "))
                        break
            self.walk(ch, cm, fs, 1)
        elif name in ("use", "tspan"):
            pass
        else:
            if len(ch):
                self.walk(ch, cm, fs, 1)

    def has_text(self, el: ET.Element) -> bool:
        return any((e.text or "").strip() for e in el.iter() if isinstance(e.tag, str) and local(e.tag) in ("text", "tspan", "div", "span", "p", "textPath"))

    # -- texte ------------------------------------------------------------
    def add(self, text: str, x: float, y: float, size: float, anchor: str = "start", lines: int = 1) -> None:
        text = clean_text(re.sub(r"\s+", " ", text)).strip()
        if text:
            self.order += 1
            self.texts.append(TextItem(text, x, y, size, self.order, anchor, lines))

    def add_text(self, el: ET.Element, cm, size: float) -> None:
        lines: List[str] = []
        cur: List[str] = []
        state = {"y": None}

        def flush() -> None:
            if cur:
                lines.append("".join(cur))
                cur.clear()

        def rec(e: ET.Element, first: bool) -> None:
            if e.text and (not first or True):
                cur.append(e.text)
            for c in e:
                if c.tag is ET.Comment or not isinstance(c.tag, str):
                    if c.tail:
                        cur.append(c.tail)
                    continue
                n = local(c.tag)
                if n in ("tspan", "textPath", "a", "tref"):
                    y = c.get("y")
                    newline = (c.get("{http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}role") == "line"
                               or (c.get("dy") not in (None, "0", "0px", "") and _f(c.get("dy")) != 0.0)
                               or (y is not None and state["y"] is not None and abs(_f(y) - state["y"]) > 0.01))
                    if newline and cur:
                        flush()
                    if y is not None:
                        state["y"] = _f(y)
                    rec(c, False)
                if c.tail:
                    cur.append(c.tail)

        state["y"] = _f(el.get("y"), None)  # type: ignore[arg-type]
        rec(el, True)
        flush()
        text = " ".join(t.strip() for t in lines if t.strip())
        if not text:
            return
        x = _f((el.get("x") or "0").split()[0].split(",")[0])
        y = _f((el.get("y") or "0").split()[0].split(",")[0])
        first_ts = next((c for c in el if isinstance(c.tag, str) and local(c.tag) == "tspan"), None)
        if el.get("x") is None and first_ts is not None:
            x = _f((first_ts.get("x") or "0").split()[0])
            y = _f((first_ts.get("y") or el.get("y") or "0").split()[0])
        ax, ay = _apply(cm, x, y)
        anchor = (_style(el).get("text-anchor") or el.get("text-anchor")
                  or (first_ts is not None and (_style(first_ts).get("text-anchor") or first_ts.get("text-anchor"))) or "start")
        self.add(text, ax, ay, size * math.sqrt(abs(cm[0] * cm[3] - cm[1] * cm[2])) if size else size, anchor, max(1, len([t for t in lines if t.strip()])))

    def matplotlib_text(self, comment: ET.Element, siblings: List[ET.Element], nxt: int, m, size: float) -> None:
        """matplotlib (svg.fonttype = path) note le texte dans un commentaire précédant les glyphes."""
        if nxt >= len(siblings):
            return
        target = siblings[nxt]
        if not isinstance(target.tag, str) or local(target.tag) != "g":
            return
        glyphs = [e for e in target.iter() if isinstance(e.tag, str) and local(e.tag) == "use"]
        text = (comment.text or "").strip()
        if not glyphs or not text or len(text) > 200 or "\n" in text:
            return
        tm = _mul(m, parse_transform(target.get("transform")))
        x, y = _apply(tm, 0, 0)
        self.add(text, x, y, size)
        self.comment_texts.append(text)

    def font_size(self, el: ET.Element, inherited: float) -> float:
        v = _style(el).get("font-size") or el.get("font-size")
        if v:
            f = _f(v, inherited)
            return f * 16 if v.strip().endswith("em") else f
        return inherited

    def reading_order(self) -> List[str]:
        items = self.texts
        if not items:
            return []
        sizes = sorted(i.size for i in items if i.size)
        med = sizes[len(sizes) // 2] if sizes else 12.0
        tol = max(4.0, med * 0.8)
        items = sorted(items, key=lambda i: (round(i.y / tol), i.x, i.order))
        out: List[str] = []
        for it in items:
            if out and out[-1] == it.text:
                continue
            out.append(it.text)
        return out

    # -- images et couleurs ------------------------------------------------------
    def image(self, el: ET.Element) -> None:
        href = el.get("{%s}href" % XLINK) or el.get("href") or ""
        m = re.match(r"data:image/([\w.+-]+);base64,(.*)$", href, re.S)
        if m:
            try:
                data = base64.b64decode(re.sub(r"\s+", "", m.group(2)))
            except Exception:
                return
            self.embedded += 1
            ext = {"jpeg": "jpg", "svg+xml": "svg"}.get(m.group(1).lower(), m.group(1).lower())
            link = self.ctx.add_asset(data, ext, stem="img")
            if link:
                self.images.append(f"![]({link})")
        elif href:
            self.images.append(f"![]({href})")

    def color_of(self, el: ET.Element) -> None:
        st = _style(el)
        for key in ("fill", "stroke", "stop-color"):
            v = (st.get(key) or el.get(key) or "").strip()
            if not v or v.lower() in _IGNORE_COLORS or v.startswith("url("):
                continue
            if _COLOR.match(v):
                v = v.lower()
                if re.match(r"^#[0-9a-f]{3}$", v):
                    v = "#" + "".join(ch * 2 for ch in v[1:])
                self.colors[v] += 1

    def source_text(self) -> str:
        parts: List[str] = []

        def rec(e: ET.Element, parent_class: str = "") -> None:
            if not isinstance(e.tag, str):
                return
            n = local(e.tag)
            if n in ("style", "script", "metadata", "namedview", "defs", "font", "glyph", "font-face"):
                return
            if _hidden(e):
                return
            if n == "title" and parent_class in ("node", "edge", "graph", "cluster"):
                return      # Graphviz : <title> = identifiant interne du nœud/lien, pas un texte affiché
            if n == "switch":
                for alt in e:
                    if isinstance(alt.tag, str) and self.has_text(alt):
                        rec(alt)
                        break
                return
            if e.text and (e.text or "").strip():
                parts.append(e.text)
            cls = (e.get("class") or "").split()[0] if n == "g" and e.get("class") else ""
            for c in e:
                if isinstance(c.tag, str):
                    rec(c, cls)
                if c.tail and c.tail.strip():
                    parts.append(c.tail)

        rec(self.root)
        parts.extend(self.comment_texts)        # les commentaires matplotlib comptent comme du texte
        return " ".join(parts)


def simplify_svg(raw: bytes) -> str:
    """Source SVG allégée : sans métadonnées d'éditeur, chemins et images tronqués."""
    s = raw.decode("utf-8", "replace")
    s = re.sub(r"<\?xml[^>]*\?>\s*", "", s)
    s = re.sub(r"<!DOCTYPE[^>]*>\s*", "", s)
    s = re.sub(r"<metadata[\s\S]*?</metadata>", "", s)
    s = re.sub(r"<sodipodi:namedview[\s\S]*?(?:/>|</sodipodi:namedview>)", "", s)
    s = re.sub(r'\s(?:inkscape|sodipodi):(?!label)[\w-]+="[^"]*"', "", s)
    s = re.sub(r'\sxmlns:(?:inkscape|sodipodi|rdf|cc|dc)="[^"]*"', "", s)
    s = re.sub(r'\sdata-[\w-]+="[^"]*"', "", s)
    s = re.sub(r'(\sd|\spoints)="([^"]{120,})"', lambda m: f'{m.group(1)}="{m.group(2)[:90].rstrip()}…"', s)
    s = re.sub(r'(href|src)="data:([\w/+.-]+);base64,[^"]*"', r'\1="data:\2;base64,…"', s)
    s = re.sub(r'\scontent="[^"]{200,}"', ' content="…"', s)
    s = re.sub(r"[ \t]+\n", "\n", s)
    s = re.sub(r"\n\s*\n+", "\n", s)
    return s.strip()


def svg_outline(root: ET.Element, raw: bytes, ctx: Ctx) -> Dict[str, object]:
    """Ce qu'un SVG intégré (page HTML, EPUB, e-mail…) apporte en texte : nom accessible, description, diagramme, libellés.

    Utilise un contexte jetable : aucune image ni avertissement n'est ajouté au document hôte.
    """
    conv = SvgConverter(root, raw, Ctx(ctx.src, ctx.opts, ctx.assets_dir), Path("inline.svg"))
    title = next((clean_text("".join(c.itertext())).strip() for c in root if local(c.tag) == "title"), "") or (root.get("aria-label") or "").strip()
    desc = next((clean_text("".join(c.itertext())).strip() for c in root if local(c.tag) == "desc"), "")
    if _AUTO_DESC.match(desc):
        desc = ""
    graph, kind = conv.recognize_graph()
    conv.walk(root, (1, 0, 0, 1, 0, 0), 12.0, 0)
    if graph is None or not graph.is_meaningful():
        graph, kind = conv.geometric_graph()
    return {"title": title, "desc": desc, "graph": graph if graph is not None and graph.is_meaningful() else None, "kind": kind,
            "texts": conv.reading_order(), "shapes": sum(conv.counts[k] for k in _SHAPES)}


@engine("svg", name="native", prio=10)
def svg_native(path, ctx: Ctx) -> Result:
    path = Path(path)
    raw = path.read_bytes()
    root = parse_xml_keep_comments(raw)
    if local(root.tag) != "svg":
        raise Unsupported("racine XML non-SVG")
    return SvgConverter(root, raw, ctx, path).run()
